# Generated by Django 2.1.2 on 2018-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181110_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='vk_id',
            field=models.BigIntegerField(default=1, verbose_name='ВК id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
