# Generated by Django 2.1.2 on 2018-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181110_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='posts',
            field=models.ManyToManyField(to='posts.Post', verbose_name='посты'),
        ),
    ]
