# Generated by Django 2.1.2 on 2018-11-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='postgroup',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='postgroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostGroup',
        ),
    ]
